### ISSUE TITLE
pip3 install failing on installing numpy on Santoku distro

### ISSUE THREAD

**Issue by bcheeves** [fireeye/stringsifter#3]
I'm trying to install this on my Santoku distro (based off Ubuntu)
It fails when it gets to running setup.py for a dependent package "numpy'
this is preventing PIP from installing the stringsifter package.

$ pip3 install numpy
Downloading/unpacking numpy
  Downloading numpy-1.17.2.zip (6.5MB): 6.5MB downloaded
  Running setup.py (path:/tmp/pip_build_santoku-bcheeves/numpy/setup.py) egg_info for package numpy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_santoku-bcheeves/numpy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_santoku-bcheeves/numpy/setup.py", line 31, in <module>

    raise RuntimeError("Python version >= 3.5 required.")

RuntimeError: Python version >= 3.5 required.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_santoku-bcheeves/numpy
Storing debug log for failure in /home/santoku-bcheeves/.pip/pip.log

I plan to lookup who supports numpy and contact them as well. Cause I have python 3.7 installed and the error clearly states that python version >= 3.5 is required :)

**Comment by bcheeves** [comment]
some info on my setup:
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.6 LTS"
```

```
$ uname -a
Linux santoku-bcheeves-vm 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ dpkg -l | grep numpy
$
```

```
$ dpkg -l | grep python3
ii  libpython3-dev:amd64                    3.4.0-0ubuntu2                                       amd64        header files and a static library for Python (default)
ii  libpython3-stdlib:amd64                 3.4.0-0ubuntu2                                       amd64        interactive high-level object-oriented language (default python3 version)
ii  libpython3.4:amd64                      3.4.3-1ubuntu1~14.04.7                               amd64        Shared Python runtime library (version 3.4)
ii  libpython3.4-dev:amd64                  3.4.3-1ubuntu1~14.04.7                               amd64        Header files and a static library for Python (v3.4)
ii  libpython3.4-minimal:amd64              3.4.3-1ubuntu1~14.04.7                               amd64        Minimal subset of the Python language (version 3.4)
ii  libpython3.4-stdlib:amd64               3.4.3-1ubuntu1~14.04.7                               amd64        Interactive high-level object-oriented language (standard library, version 3.4)
ii  python3                                 3.4.0-0ubuntu2                                       amd64        interactive high-level object-oriented language (default python3 version)
ii  python3-apport                          2.14.1-0ubuntu3.29                                   all          Python 3 library for Apport crash report handling
ii  python3-apt                             0.9.3.5ubuntu3                                       amd64        Python 3 interface to libapt-pkg
ii  python3-aptdaemon                       1.1.1-1ubuntu5.2                                     all          Python 3 module for the server and client of aptdaemon
ii  python3-aptdaemon.gtk3widgets           1.1.1-1ubuntu5.2                                     all          Python 3 GTK+ 3 widgets to run an aptdaemon client
ii  python3-cairo                           1.10.0+dfsg-3ubuntu2                                 amd64        Python 3 bindings for the Cairo vector graphics library
ii  python3-chardet                         2.2.1-2~ubuntu1                                      all          universal character encoding detector for Python3
ii  python3-colorama                        0.2.5-0.1ubuntu2                                     all          Cross-platform colored terminal text in Python - Python 3.x
ii  python3-commandnotfound                 0.3ubuntu12                                          all          Python 3 bindings for command-not-found.
ii  python3-dbus                            1.2.0-2build2                                        amd64        simple interprocess messaging system (Python 3 interface)
ii  python3-debian                          0.1.21+nmu2ubuntu2                                   all          Python 3 modules to work with Debian-related data formats
ii  python3-defer                           1.0.6-2build1                                        all          Small framework for asynchronous programming (Python 3)
ii  python3-dev                             3.4.0-0ubuntu2                                       amd64        header files and a static library for Python (default)
ii  python3-distlib                         0.1.8-1ubuntu1                                       all          low-level components of python distutils2/packaging
ii  python3-distupgrade                     1:0.220.11                                           all          manage release upgrades
ii  python3-gdbm:amd64                      3.4.3-1~14.04.2                                      amd64        GNU dbm database support for Python 3.x
ii  python3-gi                              3.12.0-1ubuntu1                                      amd64        Python 3 bindings for gobject-introspection libraries
ii  python3-gi-cairo                        3.12.0-1ubuntu1                                      amd64        Python 3 Cairo bindings for the GObject library
ii  python3-html5lib                        0.999-3~ubuntu1                                      all          HTML parser/tokenizer based on the WHATWG HTML5 specification (Python 3)
ii  python3-icu                             1.5-2ubuntu4                                         amd64        Python 3 extension wrapping the ICU C++ API
ii  python3-minimal                         3.4.0-0ubuntu2                                       amd64        minimal subset of the Python language (default python3 version)
ii  python3-packagekit                      0.8.12-1ubuntu5                                      all          PackageKit backend Python bindings
ii  python3-pam                             0.4.2-13.1ubuntu3                                    amd64        Python interface to the PAM library
ii  python3-pip                             1.5.4-1ubuntu4                                       all          alternative Python package installer - Python 3 version of the package
ii  python3-pkg-resources                   3.3-1ubuntu2                                         all          Package Discovery and Resource Access using pkg_resources
ii  python3-problem-report                  2.14.1-0ubuntu3.29                                   all          Python 3 library to handle problem reports
ii  python3-pycurl                          7.19.3-0ubuntu3                                      amd64        Python 3 bindings to libcurl
ii  python3-requests                        2.2.1-1ubuntu0.4                                     all          elegant and simple HTTP library for Python3, built for human beings
ii  python3-setuptools                      3.3-1ubuntu2                                         all          Python3 Distutils Enhancements
ii  python3-six                             1.5.2-1ubuntu1.1                                     all          Python 2 and 3 compatibility library (Python 3 interface)
ii  python3-software-properties             0.92.37.8                                            all          manage the repositories that you install software from
ii  python3-update-manager                  1:0.196.25                                           all          python 3.x module for update-manager
ii  python3-urllib3                         1.7.1-1ubuntu4.1                                     all          HTTP library with thread-safe connection pooling for Python3
ii  python3-wheel                           0.24.0-1~ubuntu1.1                                   all          built-package format for Python
ii  python3-xkit                            0.5.0ubuntu2                                         all          library for the manipulation of xorg.conf files (Python 3)
ii  python3.4                               3.4.3-1ubuntu1~14.04.7                               amd64        Interactive high-level object-oriented language (version 3.4)
ii  python3.4-dev                           3.4.3-1ubuntu1~14.04.7                               amd64        Header files and a static library for Python (v3.4)
ii  python3.4-minimal                       3.4.3-1ubuntu1~14.04.7                               amd64        Minimal subset of the Python language (version 3.4)
```

**Comment by bcheeves** [comment]
oops, my bad. that is my other box that has Python 3.7.  I can see from the output here that Python 3.4 is installed.
